### ISSUE TITLE
week1/linear_maps/python: zip and map not supported?

### ISSUE THREAD

**Issue by h35514n** [kisonecat/m2o2c2#23]
A very minor quibble:

For the first exercise, the following should work:

``` python
def vector_sum(v,w):
  return map(sum, zip(v, w))
```

All three test cases check out:

``` python
>>> vector_sum([1,2],[4,1])
[5, 3]
>>> vector_sum([-5,23],[10,2])
[5, 25]
>>> vector_sum([1,5,6],[2,3,6])
[3, 8, 12]
```

But for some reason Ximera doesn't allow it. I'm using Python 2.7.

**Comment by kisonecat** [comment]
I agree that this should work.

This is an error in Skulpt, the python interpreter we've embedded in the browser.

If you try

``` python
def mysum(x): return sum(x)
def vector_sum(v,w):
  return map(mysum, zip(v, w))
```

it will work.  Internally, skulpt calls `.func_code` but sum, being a built-in, doesn't actually have a `.func_code`.  Wrapping `sum` with `mysum` band-aids over this problem.

In the long run, we might just move to running Python server-side, instead of in the browser.

**Comment by kisonecat** [comment]
I've sent a pull request to skulpt patching this, namely https://github.com/skulpt/skulpt/pull/181
